### ISSUE TITLE
find.SOI function gives error "Error in nrow(pks) : object 'pks' not found"

### ISSUE THREAD

**Issue by Emilyzwu** [RogerGinBer/RHermes#8] opened 2021-12-27 07:23 UTC
Hi there,

I'm testing this RHermes package, just following the RHermes_UserGuide.Rmd and use the example datafile attacthed to the package (MS1TestData.mzML). When I get to the step of find.SOI, it pops out an error:

> s <- getSOIpar("double")
> myHermes <- findSOI(myHermes, s, 1)
-------- Processing SOI 1 out of 1 --------

Starting density filtering:
Running Density Filter
Running Density Interpreter
Running Density Filter
Running Density Interpreter
Now Grouping:
Merging filter 2 out of 2 with previous SOI list
Adding entries unique from the first DF
Adding entries unique from the second DF
Solving inner conflicts, Round: 1
Initial peak retrieval:

Starting group characterization:
Mass calculation:
Shortening and selecting long groups:
Error in nrow(pks) : object 'pks' not found

how should I solve this problem?
Thanks!

**Comment by RogerGinBer** [comment] 2021-12-27 09:11
Hi Emily,

I've compiled the vignette again but I haven't been able to replicate the error. Looking at the error message, I suspect it has to do with XCMS versioning, could you please run `sessionInfo()` and paste the result?

**Comment by Emilyzwu** [comment] 2021-12-28 02:19
Hi Roger,

Thanks for you reply! It seems that I have lots of packages not attached or updated properly lol - I did notice that whilst I was installing RHermes last week and some packages/dependencies kept failing to be updated so I was wondering if that is something to do with the R ver. that I'm using (3.5.3). BTW, I wasn't able to install keras and tensorflow neither (the miniconda works tho) and thus can't launch RHermesGUI(); is it also to do with my R version?

> sessionInfo()
R version 3.5.3 (2019-03-11)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19042)

Matrix products: default

locale:
[1] LC_COLLATE=English_United Kingdom.1252  LC_CTYPE=English_United Kingdom.1252   
[3] LC_MONETARY=English_United Kingdom.1252 LC_NUMERIC=C                           
[5] LC_TIME=English_United Kingdom.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] RHermes_0.99.0

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.4.6        compiler_3.5.3      pillar_1.6.4        XVector_0.22.0     
 [5] keras_2.7.0         base64enc_0.1-3     tools_3.5.3         zlibbioc_1.28.0    
 [9] zeallot_0.1.0       digest_0.6.29       lattice_0.20-38     viridisLite_0.4.0  
[13] jsonlite_1.6.1      lifecycle_1.0.1     tibble_3.0.1        gtable_0.3.0       
[17] pkgconfig_2.0.3     png_0.1-7           rlang_0.4.12        Matrix_1.2-15      
[21] igraph_1.2.5        parallel_3.5.3      fastmap_1.1.0       httr_1.4.2         
[25] dplyr_0.8.5         generics_0.1.1      Biostrings_2.50.2   S4Vectors_0.20.1   
[29] vctrs_0.3.8         htmlwidgets_1.5.4   IRanges_2.16.0      stats4_3.5.3       
[33] grid_3.5.3          tidyselect_1.0.0    reticulate_1.15     glue_1.6.0         
[37] data.table_1.12.8   R6_2.5.1            plotly_4.10.0       philentropy_0.4.0  
[41] fansi_0.4.0         BiocParallel_1.16.6 whisker_0.4         tidyr_1.0.2        
[45] ggplot2_3.2.0       purrr_0.3.4         magrittr_1.5        tfruns_1.5.0       
[49] htmltools_0.5.2     scales_1.1.1        ellipsis_0.3.2      networkD3_0.4      
[53] BiocGenerics_0.28.0 KEGGREST_1.22.0     assertthat_0.2.1    colorspace_1.4-1   
[57] tensorflow_2.7.0    utf8_1.1.4          visNetwork_2.1.0    lazyeval_0.2.2     
[61] munsell_0.5.0       crayon_1.4.2

**Comment by RogerGinBer** [comment] 2021-12-28 11:30
Hi Emily,

It seems that the R version you're using might be the cause of the errors you've been experiencing. Recent dependencies releases require R >= 4.0.0, so that's the reason you can't update them anymore. I'd strongly suggest you update your R version and reinstall the packages. 

The original error you got stems from `xcms` function `PeaksWithCentwave`, which we use to split long SOIs into smaller peaks whenever possible. If your installation is correct, the following code should return an empty matrix and raise a warning saying no peaks were found (but not an error):
`xcms::peaksWithCentWave(int = 1:10, rt = 1:10)`

Regarding the GUI not launching, I think it's also a problem with the dependencies/R version, but it's a bit strange since the sessionInfo() shows `keras` and `tensorflow` as loaded (and thus, installed). Could you share the error message you're getting when running `RHermesGUI()`? I'll be glad to help :+1:

**Comment by Emilyzwu** [comment] 2021-12-29 02:03
Hi Roger,

Thank you so much!
Yes it seems to be the R version issue. I downloaded the R 4.1.2 and re-install RHermes, problem solved! And GUI works as well.
However, I still can't get the keras and tensorflow work:


> keras::install_keras()
Collecting package metadata (current_repodata.json): ...working... failed

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "C:\Users\Emily\AppData\Local\R-MINI~1\lib\site-packages\conda\exceptions.py", line 1079, in __call__
        return func(*args, **kwargs)
      File "C:\Users\Emily\AppData\Local\R-MINI~1\lib\site-packages\conda\cli\main.py", line 84, in _main
        exit_code = do_call(args, p)
      File "C:\Users\Emily\AppData\Local\R-MINI~1\lib\site-packages\conda\cli\conda_argparse.py", line 83, in do_call
        return getattr(module, func_name)(args, parser)
      File "C:\Users\Emily\AppData\Local\R-MINI~1\lib\site-packages\conda\cli\main_create.py", line 41, in execute
        install(args, parser, 'create')
      File "C:\Users\Emily\AppData\Local\R-MINI~1\lib\site-packages\conda\cli\install.py", line 261, in install
        unlink_link_transaction = solver.solve_for_transaction(
      File "C:\Users\Emily\AppData\Local\R-MINI~1\lib\site-packages\conda\core\solve.py", line 114, in solve_for_transaction
        unlink_precs, link_precs = self.solve_for_diff(update_modifier, deps_modifier,
      File "C:\Users\Emily\AppData\Local\R-MINI~1\lib\site-packages\conda\core\solve.py", line 157, in solve_for_diff
        final_precs = self.solve_final_state(update_modifier, deps_modifier, prune, ignore_pinned,
      File "C:\Users\Emily\AppData\Local\R-MINI~1\lib\site-packages\conda\core\solve.py", line 262, in solve_final_state
        ssc = self._collect_all_metadata(ssc)
      File "C:\Users\Emily\AppData\Local\R-MINI~1\lib\site-packages\conda\common\io.py", line 88, in decorated
        return f(*args, **kwds)
      File "C:\Users\Emily\AppData\Local\R-MINI~1\lib\site-packages\conda\core\solve.py", line 425, in _collect_all_metadata
        index, r = self._prepare(prepared_specs)
      File "C:\Users\Emily\AppData\Local\R-MINI~1\lib\site-packages\conda\core\solve.py", line 1020, in _prepare
        reduced_index = get_reduced_index(self.prefix, self.channels,
      File "C:\Users\Emily\AppData\Local\R-MINI~1\lib\site-packages\conda\core\index.py", line 288, in get_reduced_index
        new_records = SubdirData.query_all(spec, channels=channels, subdirs=subdirs,
      File "C:\Users\Emily\AppData\Local\R-MINI~1\lib\site-packages\conda\core\subdir_data.py", line 140, in query_all
        result = tuple(concat(executor.map(subdir_query, channel_urls)))
      File "C:\Users\Emily\AppData\Local\R-MINI~1\lib\concurrent\futures\_base.py", line 608, in result_iterator
        yield fs.pop().result()
      File "C:\Users\Emily\AppData\Local\R-MINI~1\lib\concurrent\futures\_base.py", line 445, in result
        return self.__get_result()
      File "C:\Users\Emily\AppData\Local\R-MINI~1\lib\concurrent\futures\_base.py", line 390, in __get_result
        raise self._exception
      File "C:\Users\Emily\AppData\Local\R-MINI~1\lib\concurrent\futures\thread.py", line 52, in run
        result = self.fn(*self.args, **self.kwargs)
      File "C:\Users\Emily\AppData\Local\R-MINI~1\lib\site-packages\conda\core\subdir_data.py", line 132, in <lambda>
        subdir_query = lambda url: tuple(SubdirData(Channel(url), repodata_fn=repodata_fn).query(
      File "C:\Users\Emily\AppData\Local\R-MINI~1\lib\site-packages\conda\core\subdir_data.py", line 145, in query
        self.load()
      File "C:\Users\Emily\AppData\Local\R-MINI~1\lib\site-packages\conda\core\subdir_data.py", line 210, in load
        _internal_state = self._load()
      File "C:\Users\Emily\AppData\Local\R-MINI~1\lib\site-packages\conda\core\subdir_data.py", line 375, in _load
        raw_repodata_str = fetch_repodata_remote_request(
      File "C:\Users\Emily\AppData\Local\R-MINI~1\lib\site-packages\conda\core\subdir_data.py", line 701, in fetch_repodata_remote_request
        resp = session.get(join_url(url, filename), headers=headers, proxies=session.proxies,
      File "C:\Users\Emily\AppData\Local\R-MINI~1\lib\site-packages\requests\sessions.py", line 555, in get
        return self.request('GET', url, **kwargs)
      File "C:\Users\Emily\AppData\Local\R-MINI~1\lib\site-packages\requests\sessions.py", line 542, in request
        resp = self.send(prep, **send_kwargs)
      File "C:\Users\Emily\AppData\Local\R-MINI~1\lib\site-packages\requests\sessions.py", line 655, in send
        r = adapter.send(request, **kwargs)
      File "C:\Users\Emily\AppData\Local\R-MINI~1\lib\site-packages\requests\adapters.py", line 439, in send
        resp = conn.urlopen(
      File "C:\Users\Emily\AppData\Local\R-MINI~1\lib\site-packages\urllib3\connectionpool.py", line 696, in urlopen
        self._prepare_proxy(conn)
      File "C:\Users\Emily\AppData\Local\R-MINI~1\lib\site-packages\urllib3\connectionpool.py", line 964, in _prepare_proxy
        conn.connect()
      File "C:\Users\Emily\AppData\Local\R-MINI~1\lib\site-packages\urllib3\connection.py", line 359, in connect
        conn = self._connect_tls_proxy(hostname, conn)
      File "C:\Users\Emily\AppData\Local\R-MINI~1\lib\site-packages\urllib3\connection.py", line 500, in _connect_tls_proxy
        return ssl_wrap_socket(
      File "C:\Users\Emily\AppData\Local\R-MINI~1\lib\site-packages\urllib3\util\ssl_.py", line 453, in ssl_wrap_socket
        ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls)
      File "C:\Users\Emily\AppData\Local\R-MINI~1\lib\site-packages\urllib3\util\ssl_.py", line 495, in _ssl_wrap_socket_impl
        return ssl_context.wrap_socket(sock)
      File "C:\Users\Emily\AppData\Local\R-MINI~1\lib\ssl.py", line 500, in wrap_socket
        return self.sslsocket_class._create(
      File "C:\Users\Emily\AppData\Local\R-MINI~1\lib\ssl.py", line 997, in _create
        raise ValueError("check_hostname requires server_hostname")
    ValueError: check_hostname requires server_hostname

`$ C:\Users\Emily\AppData\Local\R-MINI~1\Scripts\conda-script.py create --yes --prefix C:/Users/Emily/AppData/Local/r-miniconda/envs/r-reticulate python=3.6 numpy -c conda-forge`

  environment variables:
                 CIO_TEST=<not set>
                CONDA_EXE=C:\Users\Emily\AppData\Local\R-MINI~1\condabin\..\Scripts\conda.exe
               CONDA_EXES="C:\Users\Emily\AppData\Local\R-MINI~1\condabin\..\Scripts\conda.exe"
               CONDA_ROOT=C:\Users\Emily\AppData\Local\R-MINI~1
           CURL_CA_BUNDLE=<not set>
                 HOMEPATH=\Users\Emily
                     PATH=C:\Users\Emily\AppData\Local\R-MINI~1;C:\Users\Emily\AppData\Local\R-M
                          INI~1\Library\mingw-w64\bin;C:\Users\Emily\AppData\Local\R-MINI~1\Libr
                          ary\usr\bin;C:\Users\Emily\AppData\Local\R-MINI~1\Library\bin;C:\Users
                          \Emily\AppData\Local\R-MINI~1\Scripts;C:\Users\Emily\AppData\Local\R-M
                          INI~1\bin;C:\Program Files\R\R-4.1.2\bin\x64;C:\Program Files
                          (x86)\Common Files\Oracle\Java\javapath;C:\Windows\system32;C:\Windows
                          ;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;
                          C:\Program Files (x86)\Common Files\lenovo\easyplussdk\bin;C:\Program
                          Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program
                          Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessComm
                          on\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS
                          \System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\User
                          s\Emily\AppData\Local\Microsoft\WindowsApps;
             PSMODULEPATH=C:\Program Files\WindowsPowerShell\Modules;C:\WINDOWS\system32\Windows
                          PowerShell\v1.0\Modules
       REQUESTS_CA_BUNDLE=<not set>
   RMARKDOWN_MATHJAX_PATH=C:/Program Files/RStudio/resources/mathjax-26
        RS_RPOSTBACK_PATH=C:/Program Files/RStudio/bin/rpostback
            SSL_CERT_FILE=<not set>

     active environment : None
       user config file : C:\Users\Emily\.condarc
 populated config files : 
          conda version : 4.10.3
    conda-build version : not installed
         python version : 3.9.5.final.0
       virtual packages : __cuda=8.0=0
                          __win=0=0
                          __archspec=1=x86_64
       base environment : C:\Users\Emily\AppData\Local\R-MINI~1  (writable)
      conda av data dir : C:\Users\Emily\AppData\Local\R-MINI~1\etc\conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\Emily\AppData\Local\R-MINI~1\pkgs
                          C:\Users\Emily\.conda\pkgs
                          C:\Users\Emily\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\Emily\AppData\Local\R-MINI~1\envs
                          C:\Users\Emily\.conda\envs
                          C:\Users\Emily\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.10.3 requests/2.25.1 CPython/3.9.5 Windows/10 Windows/10.0.19042
          administrator : False
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.

Upload did not complete.
Error: Error 1 occurred creating conda environment C:/Users/Emily/AppData/Local/r-miniconda/envs/r-reticulate
> tensorflow::install_tensorflow()
Collecting package metadata (current_repodata.json): ...working... failed

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "C:\Users\Emily\AppData\Local\R-MINI~1\lib\site-packages\conda\exceptions.py", line 1079, in __call__
        return func(*args, **kwargs)
      File "C:\Users\Emily\AppData\Local\R-MINI~1\lib\site-packages\conda\cli\main.py", line 84, in _main
        exit_code = do_call(args, p)
      File "C:\Users\Emily\AppData\Local\R-MINI~1\lib\site-packages\conda\cli\conda_argparse.py", line 83, in do_call
        return getattr(module, func_name)(args, parser)
      File "C:\Users\Emily\AppData\Local\R-MINI~1\lib\site-packages\conda\cli\main_create.py", line 41, in execute
        install(args, parser, 'create')
      File "C:\Users\Emily\AppData\Local\R-MINI~1\lib\site-packages\conda\cli\install.py", line 261, in install
        unlink_link_transaction = solver.solve_for_transaction(
      File "C:\Users\Emily\AppData\Local\R-MINI~1\lib\site-packages\conda\core\solve.py", line 114, in solve_for_transaction
        unlink_precs, link_precs = self.solve_for_diff(update_modifier, deps_modifier,
      File "C:\Users\Emily\AppData\Local\R-MINI~1\lib\site-packages\conda\core\solve.py", line 157, in solve_for_diff
        final_precs = self.solve_final_state(update_modifier, deps_modifier, prune, ignore_pinned,
      File "C:\Users\Emily\AppData\Local\R-MINI~1\lib\site-packages\conda\core\solve.py", line 262, in solve_final_state
        ssc = self._collect_all_metadata(ssc)
      File "C:\Users\Emily\AppData\Local\R-MINI~1\lib\site-packages\conda\common\io.py", line 88, in decorated
        return f(*args, **kwds)
      File "C:\Users\Emily\AppData\Local\R-MINI~1\lib\site-packages\conda\core\solve.py", line 425, in _collect_all_metadata
        index, r = self._prepare(prepared_specs)
      File "C:\Users\Emily\AppData\Local\R-MINI~1\lib\site-packages\conda\core\solve.py", line 1020, in _prepare
        reduced_index = get_reduced_index(self.prefix, self.channels,
      File "C:\Users\Emily\AppData\Local\R-MINI~1\lib\site-packages\conda\core\index.py", line 288, in get_reduced_index
        new_records = SubdirData.query_all(spec, channels=channels, subdirs=subdirs,
      File "C:\Users\Emily\AppData\Local\R-MINI~1\lib\site-packages\conda\core\subdir_data.py", line 140, in query_all
        result = tuple(concat(executor.map(subdir_query, channel_urls)))
      File "C:\Users\Emily\AppData\Local\R-MINI~1\lib\concurrent\futures\_base.py", line 608, in result_iterator
        yield fs.pop().result()
      File "C:\Users\Emily\AppData\Local\R-MINI~1\lib\concurrent\futures\_base.py", line 445, in result
        return self.__get_result()
      File "C:\Users\Emily\AppData\Local\R-MINI~1\lib\concurrent\futures\_base.py", line 390, in __get_result
        raise self._exception
      File "C:\Users\Emily\AppData\Local\R-MINI~1\lib\concurrent\futures\thread.py", line 52, in run
        result = self.fn(*self.args, **self.kwargs)
      File "C:\Users\Emily\AppData\Local\R-MINI~1\lib\site-packages\conda\core\subdir_data.py", line 132, in <lambda>
        subdir_query = lambda url: tuple(SubdirData(Channel(url), repodata_fn=repodata_fn).query(
      File "C:\Users\Emily\AppData\Local\R-MINI~1\lib\site-packages\conda\core\subdir_data.py", line 145, in query
        self.load()
      File "C:\Users\Emily\AppData\Local\R-MINI~1\lib\site-packages\conda\core\subdir_data.py", line 210, in load
        _internal_state = self._load()
      File "C:\Users\Emily\AppData\Local\R-MINI~1\lib\site-packages\conda\core\subdir_data.py", line 375, in _load
        raw_repodata_str = fetch_repodata_remote_request(
      File "C:\Users\Emily\AppData\Local\R-MINI~1\lib\site-packages\conda\core\subdir_data.py", line 701, in fetch_repodata_remote_request
        resp = session.get(join_url(url, filename), headers=headers, proxies=session.proxies,
      File "C:\Users\Emily\AppData\Local\R-MINI~1\lib\site-packages\requests\sessions.py", line 555, in get
        return self.request('GET', url, **kwargs)
      File "C:\Users\Emily\AppData\Local\R-MINI~1\lib\site-packages\requests\sessions.py", line 542, in request
        resp = self.send(prep, **send_kwargs)
      File "C:\Users\Emily\AppData\Local\R-MINI~1\lib\site-packages\requests\sessions.py", line 655, in send
        r = adapter.send(request, **kwargs)
      File "C:\Users\Emily\AppData\Local\R-MINI~1\lib\site-packages\requests\adapters.py", line 439, in send
        resp = conn.urlopen(
      File "C:\Users\Emily\AppData\Local\R-MINI~1\lib\site-packages\urllib3\connectionpool.py", line 696, in urlopen
        self._prepare_proxy(conn)
      File "C:\Users\Emily\AppData\Local\R-MINI~1\lib\site-packages\urllib3\connectionpool.py", line 964, in _prepare_proxy
        conn.connect()
      File "C:\Users\Emily\AppData\Local\R-MINI~1\lib\site-packages\urllib3\connection.py", line 359, in connect
        conn = self._connect_tls_proxy(hostname, conn)
      File "C:\Users\Emily\AppData\Local\R-MINI~1\lib\site-packages\urllib3\connection.py", line 500, in _connect_tls_proxy
        return ssl_wrap_socket(
      File "C:\Users\Emily\AppData\Local\R-MINI~1\lib\site-packages\urllib3\util\ssl_.py", line 453, in ssl_wrap_socket
        ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls)
      File "C:\Users\Emily\AppData\Local\R-MINI~1\lib\site-packages\urllib3\util\ssl_.py", line 495, in _ssl_wrap_socket_impl
        return ssl_context.wrap_socket(sock)
      File "C:\Users\Emily\AppData\Local\R-MINI~1\lib\ssl.py", line 500, in wrap_socket
        return self.sslsocket_class._create(
      File "C:\Users\Emily\AppData\Local\R-MINI~1\lib\ssl.py", line 997, in _create
        raise ValueError("check_hostname requires server_hostname")
    ValueError: check_hostname requires server_hostname

`$ C:\Users\Emily\AppData\Local\R-MINI~1\Scripts\conda-script.py create --yes --prefix C:/Users/Emily/AppData/Local/r-miniconda/envs/r-reticulate python=3.6 numpy -c conda-forge`

  environment variables:
                 CIO_TEST=<not set>
                CONDA_EXE=C:\Users\Emily\AppData\Local\R-MINI~1\condabin\..\Scripts\conda.exe
               CONDA_EXES="C:\Users\Emily\AppData\Local\R-MINI~1\condabin\..\Scripts\conda.exe"
               CONDA_ROOT=C:\Users\Emily\AppData\Local\R-MINI~1
           CURL_CA_BUNDLE=<not set>
                 HOMEPATH=\Users\Emily
                     PATH=C:\Users\Emily\AppData\Local\R-MINI~1;C:\Users\Emily\AppData\Local\R-M
                          INI~1\Library\mingw-w64\bin;C:\Users\Emily\AppData\Local\R-MINI~1\Libr
                          ary\usr\bin;C:\Users\Emily\AppData\Local\R-MINI~1\Library\bin;C:\Users
                          \Emily\AppData\Local\R-MINI~1\Scripts;C:\Users\Emily\AppData\Local\R-M
                          INI~1\bin;C:\Program Files\R\R-4.1.2\bin\x64;C:\Program Files
                          (x86)\Common Files\Oracle\Java\javapath;C:\Windows\system32;C:\Windows
                          ;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;
                          C:\Program Files (x86)\Common Files\lenovo\easyplussdk\bin;C:\Program
                          Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program
                          Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessComm
                          on\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS
                          \System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\User
                          s\Emily\AppData\Local\Microsoft\WindowsApps;
             PSMODULEPATH=C:\Program Files\WindowsPowerShell\Modules;C:\WINDOWS\system32\Windows
                          PowerShell\v1.0\Modules
       REQUESTS_CA_BUNDLE=<not set>
   RMARKDOWN_MATHJAX_PATH=C:/Program Files/RStudio/resources/mathjax-26
        RS_RPOSTBACK_PATH=C:/Program Files/RStudio/bin/rpostback
            SSL_CERT_FILE=<not set>

     active environment : None
       user config file : C:\Users\Emily\.condarc
 populated config files : 
          conda version : 4.10.3
    conda-build version : not installed
         python version : 3.9.5.final.0
       virtual packages : __cuda=8.0=0
                          __win=0=0
                          __archspec=1=x86_64
       base environment : C:\Users\Emily\AppData\Local\R-MINI~1  (writable)
      conda av data dir : C:\Users\Emily\AppData\Local\R-MINI~1\etc\conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\Emily\AppData\Local\R-MINI~1\pkgs
                          C:\Users\Emily\.conda\pkgs
                          C:\Users\Emily\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\Emily\AppData\Local\R-MINI~1\envs
                          C:\Users\Emily\.conda\envs
                          C:\Users\Emily\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.10.3 requests/2.25.1 CPython/3.9.5 Windows/10 Windows/10.0.19042
          administrator : False
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.

Upload did not complete.
Error: Error 1 occurred creating conda environment C:/Users/Emily/AppData/Local/r-miniconda/envs/r-reticulate

**Comment by Emilyzwu** [comment] 2021-12-29 02:26
And weirdly, I did find both the keras and tensorflow folder in my R library.

**Comment by RogerGinBer** [comment] 2021-12-29 09:34
Hi Emily,

The R packages `keras` and `tensorflow` serve just as interfaces to _work_ with the Python installation, which is the one giving you the errors above. Luckily, a working Python installation is no longer required to run `RHermes`, as we have implemented a simpler blank subtraction method based on cosine elution similarity for when the user doesn't have Python configured. I'll merge the _devel_ branch later today, where I have fixed small bugs regarding that blank subtraction method, so I advise you update.

In case you still want to configure keras and tensorflow, I've found this issue that may be useful (same error code): https://github.com/conda/conda/issues/10590. If you haven't, you could alse give the alternative installation method a try (see README.md), where you open a miniconda terminal (from the Start Menu, it's called Anaconda Prompt) and run:
`conda create -n newenv python=3.6 tensorflow keras`

When finished, from R you run:
`reticulate::use_condaenv("newenv", required = TRUE)`

**Comment by Emilyzwu** [comment] 2021-12-29 09:41
Brilliant! Guess I'll just wait for the update :)

I've tried manual installation already and it gave me the similar error msg as shown in R...so I'll just leave it and update the RHermes later.

Wish you a Happy New Year :)

**Comment by RogerGinBer** [comment] 2021-12-29 10:22
Happy New Year! 
If there are no further problems, I'll go ahead and close the issue :+1:

**Closed as completed by RogerGinBer** 2021-12-29 10:22 UTC
